name: Build and Release WSL2 Distro

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          file: ./docker/Dockerfile
          push: false
          tags: wsl2-distro:latest

      - name: Export WSL2 Distro as Tar
        run: |
          chmod +x ./scripts/export-tar.sh
          ./scripts/export-tar.sh

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload WSL2 Distro Tar
        uses: actions/upload-artifact@v2
        with:
          name: wsl2-distro
          path: ./path/to/your/tarfile.tar  # Update with the actual path to the tar file generated by export-tar.sh

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag: ${{ github.event.release.tag }}
          files: ./path/to/your/tarfile.tar  # Update with the actual path to the tar file generated by export-tar.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}